apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opensearch-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: opensearch-sa
    namespace: opensearch
roleRef:
  kind: ClusterRole
  name: opensearch-clusterrole
  apiGroup: rbac.authorization.k8s.io