apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-debug
  namespace: minio
  labels:
    app.kubernetes.io/name: minio-debug
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: minio-debug
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio-debug
    spec:
      serviceAccountName: minio
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      initContainers:
        - name: copy-certs
          image: busybox:1.34.1
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          command: [ "sh", "-c" ]
          args:
            - |              
              mkdir -p .mc/certs
              cp -f /tmp/minio/debug-certs/* .mc/certs
              cp -f /tmp/minio/certs/* .mc/certs
              chmod 0400 .mc/certs/*.key

              mkdir -p .mc/certs/CAs
              cp .mc/certs/ca.crt .mc/certs/CAs/ca.crt

              echo "successfully copied certs"
          volumeMounts:
            - name: certs-secrets
              mountPath: /tmp/minio/certs
            - name: debug-certs-secrets
              mountPath: /tmp/minio/debug-certs
            - name: data
              mountPath: .mc
              readOnly: false
        - name: init-config
          image: minio/mc:RELEASE.2022-11-17T21-20-39Z
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          command: ["sh", "-c"]
          args:
            - |
              mc config host add minio-0 https://minio-0.minio.minio.svc.cluster.local:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-root
                  key: username
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-root
                  key: password
          volumeMounts:
            - name: data
              mountPath: .mc
              readOnly: false
      containers:
        - name: minio-cli
          image: minio/mc:RELEASE.2022-11-17T21-20-39Z
          securityContext:
            runAsNonRoot: true
            runAsUser: 65534
            runAsGroup: 65534
          command: [ "sh" ]
          args: [ "-c", "sleep infinity" ]
          volumeMounts:
            - name: data
              mountPath: .mc
              readOnly: false
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data-minio-debug
        - name: debug-certs-secrets
          projected:
            sources:
              - secret:
                  name: minio-debug-certs
                  items:
                    - key: tls.crt
                      path: public.crt
                      mode: 256
                    - key: tls.key
                      path: private.key
                      mode: 256
        - name: certs-secrets
          projected:
            sources:
              - secret:
                  name: minio-server-certs
                  items:
                    - key: ca.crt
                      path: ca.crt
                      mode: 256