apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-minio-debug
  namespace: minio
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi