apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: minio-readonly-certs
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  isCA: false
  secretName: minio-readonly-certs
  commonName: readonly
  duration: 9000h
  renewBefore: 180h
  usages:
    - digital signature
    - key encipherment
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  subject:
    organizations:
      - minio
  dnsNames:
    - "localhost"
    - "127.0.0.1"
    - "*.minio.minio.svc.cluster.local"
  issuerRef:
    name: ca-issuer
    kind: Issuer
    group: cert-manager.io