---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
  labels:
    app.kubernetes.io/name: minio
spec:
  serviceName: minio
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: minio
  template:
    metadata:
      labels:
        app.kubernetes.io/name: minio
    spec:
      serviceAccountName: minio
      automountServiceAccountToken: false
      initContainers:
        - name: copy-certs
          image: busybox:1.34.1
          command: [ "sh", "-c"]
          args:
            - |
              cp -f /tmp/minio/certs/* /etc/minio/certs/
              chmod 0400 /etc/minio/certs/*.key
              
              mkdir /etc/minio/certs/CAs
              mv /etc/minio/certs/ca.crt /etc/minio/certs/CAs/ca.crt
              
              echo "successfully copied certs"
          volumeMounts:
            - name: certs
              mountPath: /etc/minio/certs
            - name: certs-secrets
              mountPath: /tmp/minio/certs
      containers:
        - name: server
          image: minio/minio:RELEASE.2022-11-29T23-40-49Z
          livenessProbe:
            httpGet:
              path: /minio/health/live
              port: server
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /minio/health/ready
              port: server
              scheme: HTTPS
          ports:
            - containerPort: 9000
              name: server
              protocol: TCP
          args:
          - minio
          - server
          - minio-0.minio.minio.svc.cluster.local
          - --config-dir=/data/config
          - --certs-dir=/etc/minio/certs
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-root
                  key: username
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-root
                  key: password
          volumeMounts:
            - name: data
              mountPath: /data/db
              readOnly: false
              subPath: db
            - name: data
              mountPath: /data/config
              readOnly: false
              subPath: config
            - name: certs
              mountPath: /etc/minio/certs
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: data
        - name: certs
          emptyDir: { }
        - name: certs-secrets
          projected:
            sources:
              - secret:
                  name: minio-server-certs
                  items:
                    - key: ca.crt
                      path: ca.crt
                      mode: 256
                    - key: tls.crt
                      path: public.crt
                      mode: 256
                    - key: tls.key
                      path: private.key
                      mode: 256
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app.kubernetes.io/name: minio
      spec:
        storageClassName: standard
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
