apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-certificate
  namespace: mtls
  labels:
    app.kubernetes.io/name: mtls
spec:
  isCA: false
  secretName: mtls-certs
  duration: 9000h
  renewBefore: 180h
  usages:
    - digital signature
    - key encipherment
    - client auth
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
    - "localhost"
    - "127.0.0.1"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
    group: cert-manager.io